# Generated by Django 2.2.2 on 2019-06-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(default='', max_length=400),
        ),
    ]
