# Generated by Django 2.2.2 on 2019-06-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100)),
                ('picture', models.CharField(default='', max_length=100)),
                ('guestsize', models.IntegerField()),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
            ],
        ),
    ]
