# Generated by Django 2.2.2 on 2019-06-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify_app', '0002_auto_20190622_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='location',
            name='picture',
            field=models.CharField(default='', max_length=400),
        ),
    ]
