# Generated by Django 2.2.2 on 2019-06-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify_app', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
