# Generated by Django 2.2.2 on 2019-06-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify_app', '0003_auto_20190622_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
