# Generated by Django 2.2.2 on 2019-06-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify_app', '0004_auto_20190624_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='location',
            name='picture',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
